// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTrack(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetPublicTrack(ctx context.Context, id uuid.UUID) (Track, error)
	GetTrack(ctx context.Context, id uuid.UUID) (Track, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListUserTracks(ctx context.Context, userID uuid.NullUUID) ([]Track, error)
	UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
