// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, display_name, avatar_url, oauth_provider, oauth_id
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, email, display_name, avatar_url, oauth_provider, oauth_id, storage_used, storage_limit, created_at, updated_at
`

type CreateUserParams struct {
	Email         string      `json:"email"`
	DisplayName   pgtype.Text `json:"display_name"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
	OauthProvider string      `json:"oauth_provider"`
	OauthID       string      `json:"oauth_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.OauthProvider,
		arg.OauthID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.OauthProvider,
		&i.OauthID,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, display_name, avatar_url, oauth_provider, oauth_id, storage_used, storage_limit, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.OauthProvider,
		&i.OauthID,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_url, oauth_provider, oauth_id, storage_used, storage_limit, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.OauthProvider,
		&i.OauthID,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuth = `-- name: GetUserByOAuth :one
SELECT id, email, display_name, avatar_url, oauth_provider, oauth_id, storage_used, storage_limit, created_at, updated_at FROM users
WHERE oauth_provider = $1 AND oauth_id = $2
LIMIT 1
`

type GetUserByOAuthParams struct {
	OauthProvider string `json:"oauth_provider"`
	OauthID       string `json:"oauth_id"`
}

func (q *Queries) GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOAuth, arg.OauthProvider, arg.OauthID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.OauthProvider,
		&i.OauthID,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = $2, avatar_url = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, email, display_name, avatar_url, oauth_provider, oauth_id, storage_used, storage_limit, created_at, updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.OauthProvider,
		&i.OauthID,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStorage = `-- name: UpdateUserStorage :exec
UPDATE users
SET storage_used = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserStorageParams struct {
	ID          uuid.UUID   `json:"id"`
	StorageUsed pgtype.Int8 `json:"storage_used"`
}

func (q *Queries) UpdateUserStorage(ctx context.Context, arg UpdateUserStorageParams) error {
	_, err := q.db.Exec(ctx, updateUserStorage, arg.ID, arg.StorageUsed)
	return err
}
